spring.application.name=cinegamingapi

spring.datasource.url=jdbc:mysql://localhost:3306/cinegaming_api?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERMYSQL}
spring.datasource.password=${DB_PASSWORDMYSQL}

server.error.include-stacktrace=never